// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.RobotContainer;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class MoveForward extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    public RobotContainer m_robotContainer = RobotContainer.getInstance();

    private double m_goalDistance;
    private double targetIntensity;
    private double tolerance;

    private double distanceTravelled;

 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public MoveForward(double intensity, double goalDistance, double tolerance) {
        targetIntensity=intensity;
        m_goalDistance = goalDistance;
        this.tolerance = tolerance;


    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        m_robotContainer.m_driveSub.drive(0, 0);
        m_robotContainer.m_driveSub.resetGyro();
        m_robotContainer.m_driveSub.resetEncoder();
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        
        double yawIntensity = (m_robotContainer.m_driveSub.getGyroAngle())/100;
        m_robotContainer.m_driveSub.drive((targetIntensity + yawIntensity),(targetIntensity - yawIntensity));
        distanceTravelled = m_robotContainer.m_driveSub.getEncoderDistance();


    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {

        m_robotContainer.m_driveSub.drive(0, 0);
        m_robotContainer.m_driveSub.resetGyro();
        m_robotContainer.m_driveSub.resetEncoder();
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        if(distanceTravelled < m_goalDistance - tolerance)
        {
            return true;
        }
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;
    
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
